[default]
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
remappings = [
  "@ds=lib/ds-test/src/",
  "@solmate=lib/solmate/src/",
  "@std=lib/forge-std/src/",
  "@openzeppelin=lib/openzeppelin-contracts",
]

# See more config options https://github.com/gakonst/foundry/tree/master/config
